/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.edunova.ljubavnikalkulator;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Ivan
 */
public class Prozor extends javax.swing.JFrame {

    int zbroj;

    /**
     * Creates new form Prozor
     */
    public Prozor() {
        initComponents();
        txtPrvaOsoba.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPrvaOsoba = new javax.swing.JTextField();
        txtDrugaOsoba = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIzracunaj = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();
        lblIzracun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 230, 247));
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        lblNaslov.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        lblNaslov.setForeground(new java.awt.Color(180, 80, 0));
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("Izračunajte koliki je postotak ljubavi dvije osobe");

        txtPrvaOsoba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrvaOsobaKeyPressed(evt);
            }
        });

        txtDrugaOsoba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDrugaOsobaKeyPressed(evt);
            }
        });

        jLabel1.setText("Ime prve osobe");

        jLabel2.setText("Ime druge osobe");

        btnIzracunaj.setText("Izračunaj");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtPrvaOsoba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDrugaOsoba)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btnIzracunaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrvaOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDrugaOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnIzracunaj)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        lblIcon.setMinimumSize(new java.awt.Dimension(100, 100));

        lblIzracun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(lblIzracun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIzracun, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed
        if (txtPrvaOsoba.getText().length() == 0
                || txtDrugaOsoba.getText().length() == 0) {
            lblIzracun.setText("Obavezno unesite imena obje osobe");
            lblIcon.setIcon(null);
        } else {
            izracunaj();
        }
    }//GEN-LAST:event_btnIzracunajActionPerformed

    private void txtDrugaOsobaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrugaOsobaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnIzracunajActionPerformed(null);
        }
    }//GEN-LAST:event_txtDrugaOsobaKeyPressed

    private void txtPrvaOsobaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrvaOsobaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDrugaOsoba.requestFocus();
        }
     }//GEN-LAST:event_txtPrvaOsobaKeyPressed

    private void izracunaj() {
        String prvaOsoba, drugaOsoba, sveZajednoBezRazmaka, ispis;
        prvaOsoba = makniCrticeIRazmake(txtPrvaOsoba.getText().toLowerCase());
        drugaOsoba = makniCrticeIRazmake(txtDrugaOsoba.getText().toLowerCase());
        sveZajednoBezRazmaka = prvaOsoba + drugaOsoba;
        List<Character> nizSvihZnakova = new ArrayList<Character>();
        List<Integer> pocetniNizBrojeva = new ArrayList<Integer>();
        for (char znak : sveZajednoBezRazmaka.toCharArray()) {
            nizSvihZnakova.add(znak);
        }
        for (char broj : nizSvihZnakova) {
            pocetniNizBrojeva.add(prebrojiZnakove(broj, nizSvihZnakova));
        }
        zbroji(pocetniNizBrojeva);
        ispis = prvaVelikaSlova(txtPrvaOsoba.getText()) + " i "
                + prvaVelikaSlova(txtDrugaOsoba.getText())
                + " se vole " + zbroj + "%";
        lblIzracun.setText(ispis);
        postaviSliku(zbroj);
    }

    private void zbroji(List<Integer> nizBrojeva) {
        List<Integer> provjereniNizBrojeva = new ArrayList<Integer>();
        nizBrojeva.forEach(brojZaProvjeru -> {
            if (brojZaProvjeru > 9) {
                provjereniNizBrojeva.add(brojZaProvjeru / 10);
                int ostatak = brojZaProvjeru % 10;
                if (ostatak != 0) {
                    provjereniNizBrojeva.add(ostatak);
                }
            } else {
                provjereniNizBrojeva.add(brojZaProvjeru);
            }
        });
        int velicinaNiza = provjereniNizBrojeva.size();
        if (velicinaNiza < 3 && jeLiManjiOd100(provjereniNizBrojeva)) {
            zbroj = listToInt(provjereniNizBrojeva);
        } else {
            List<Integer> noviNiz = new ArrayList<Integer>();
            if (velicinaNiza % 2 == 0) {
                iterirajParno(velicinaNiza, provjereniNizBrojeva, noviNiz);
            } else {
                iterirajNeparno(velicinaNiza, provjereniNizBrojeva, noviNiz);
            }
            zbroji(noviNiz);
        }
    }

    private static void iterirajNeparno(int velicinaNiza, List<Integer> provjereniNizBrojeva, List<Integer> noviNiz) {
        int breakpoint = velicinaNiza / 2;
        for (int i = 0; i <= breakpoint; i++) {
            int zadnji = (velicinaNiza - i) - 1;
            if (i == zadnji) {
                noviNiz.add(provjereniNizBrojeva.get(i));
            } else {
                noviNiz.add(provjereniNizBrojeva.get(i) + provjereniNizBrojeva.get(zadnji));
            }
        }
    }

    private static void iterirajParno(int velicinaNiza, List<Integer> provjereniNizBrojeva, List<Integer> noviNiz) {
        int breakpoint = (velicinaNiza / 2) - 1;
        for (int i = 0; i <= breakpoint; i++) {
            int zadnji = (velicinaNiza - i) - 1;
            noviNiz.add(provjereniNizBrojeva.get(i) + provjereniNizBrojeva.get(zadnji));
        }
    }

    private static boolean jeLiManjiOd100(List<Integer> nizBrojeva) {
        int ukupno = listToInt(nizBrojeva);
        return ukupno <= 100;

    }

    private static int listToInt(List<Integer> nizBrojeva) {
        int brojKojegSeVraca = 0;
        for (Integer broj : nizBrojeva) {
            brojKojegSeVraca = (brojKojegSeVraca * 10) + broj;
        }
        return brojKojegSeVraca;
    }

    private static int prebrojiZnakove(char znak, List<Character> nizZnakova) {
        int brojPojava = 0;
        for (char pojediniZnak : nizZnakova) {
            if (pojediniZnak == znak) {
                brojPojava++;
            }
        }
        return brojPojava;
    }

    protected String prvaVelikaSlova(String str) {
        str = str.trim().toLowerCase();
        String novo;
        List<String> arr = new ArrayList<String>();
        List<String> arr2 = new ArrayList<String>();
        String[] rijecSplitted = str.split(" ");
        for (String spltd : rijecSplitted) {
            arr.add(srediIme(spltd));

        }
        novo = String.join(" ", arr);
        String[] rijecSplitted2 = novo.split("-");
        for (String spltd2 : rijecSplitted2) {
            arr2.add(srediIme(spltd2));
        }
        return String.join("-", arr2);
    }

    private String srediIme(String s) {
        try {
            s = s.trim();
            return s.substring(0, 1).toUpperCase() + s.substring(1);
        } catch (Exception e) {
            return s;
        }
    }

    private String makniCrticeIRazmake(String ime) {
        return ime.replace("-", "").replace(" ", "");
    }

    private void postaviSliku(int zbroj) {
        // putanju potrebno promijeniti ovisno o lokaciji
        String rootPutanja = "C:\\Users\\Ivan\\Documents\\NetBeansProjects\\"
                + "LjubavniKalkulatorSwing\\LjubavniKalkulator\\src\\main\\"
                + "java\\hr\\edunova\\ljubavnikalkulator\\";
        String putanja = rootPutanja + "brokenHeart.png";

        if (zbroj >= 30 && zbroj < 50) {
            putanja = rootPutanja + "notHappyHeart.png";
        }
        if (zbroj >= 50 && zbroj < 80) {
            putanja = rootPutanja + "smileyHeart.png";
        }
        if (zbroj >= 80) {
            putanja = rootPutanja + "goldenHeart.png";
        }
        ImageIcon icon = new ImageIcon(putanja);
        Image image = icon.getImage();
        Image imageScaled = image.getScaledInstance(
                lblIcon.getWidth(), 
                lblIcon.getHeight(), 
                Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScaled);
        lblIcon.setIcon(scaledIcon);
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIzracun;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JTextField txtDrugaOsoba;
    private javax.swing.JTextField txtPrvaOsoba;
    // End of variables declaration//GEN-END:variables

}
